#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_ELECTRICAL_SENSOR_ENABLED
#define AP_ELECTRICAL_SENSOR_ENABLED 0
#endif

#ifndef AP_ELECTRICAL_SENSOR_BACKEND_DEFAULT_ENABLED
#define AP_ELECTRICAL_SENSOR_BACKEND_DEFAULT_ENABLED AP_ELECTRICAL_SENSOR_ENABLED
#endif

#ifndef AP_ELECTRICAL_SENSOR_DRONECAN_ENABLED
    #define AP_ELECTRICAL_SENSOR_DRONECAN_ENABLED AP_ELECTRICAL_SENSOR_BACKEND_DEFAULT_ENABLED && HAL_ENABLE_DRONECAN_DRIVERS
#endif
#if AP_ELECTRICAL_SENSOR_DRONECAN_ENABLED && !HAL_ENABLE_DRONECAN_DRIVERS
    #error AP_ELECTRICAL_SENSOR_DRONECAN_ENABLED requires HAL_ENABLE_DRONECAN_DRIVERS
#endif

// maximum number of Electrical Sensors
#ifndef AP_ELECTRICAL_SENSOR_MAX_INSTANCES
#define AP_ELECTRICAL_SENSOR_MAX_INSTANCES             3
#endif

// first sensor is always the primary sensor
#ifndef AP_ELECTRICAL_SENSOR_PRIMARY_INSTANCE
#define AP_ELECTRICAL_SENSOR_PRIMARY_INSTANCE          0
#endif

